#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 
#2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
#By considering the terms in the Fibonacci sequence whose values donot exceed four million, find the sum
#of even valued terms

tot = 0;
n = [1, 2]  # Starting list
for x in range(2, 32):  # Generate the first 10 Fibonacci numbers
    n.append(n[x-1] + n[x-2])  # Add the next Fibonacci number
print(n)
for total in n:
    if(total % 2 == 0):
        #print(type(total))
        tot += total
print(tot)

